### ISSUE TITLE
Fails in Mx 7.11

### ISSUE THREAD

**Issue by rickyv3** [mendixlabs/range-slider#8] opened 2018-03-23 17:31 UTC
Run into the following error in 7.11:

TypeError: Cannot read property 'toFixed' of undefined
    at Object.f [as b] (RangeSlider.js?636574041495279473:6)
    at n.value (RangeSlider.js?636574041495279473:11)
    at RangeSlider.js?636574041495279473:11
    at Array.map (<anonymous>)
    at n.value (RangeSlider.js?636574041495279473:11)
    at updateClassInstance (mxui.js?636574041495279473:7)
    at beginWork (mxui.js?636574041495279473:7)
    at i (mxui.js?636574041495279473:7)
    at u (mxui.js?636574041495279473:7)
    at c (mxui.js?636574041495279473:7)

**Comment by akileng56** [comment] 2018-03-26 07:31
Hi, @rickyv3 thanks for raising this. However, we are not able to reproduce the issue.
Could you please send us a sample project(.mpk) where we can reproduce the issue from.

**Comment by Andries-Smit** [comment] 2018-03-26 08:48
Looking at the code its likely got something to do with the max, min and markers setting.
https://github.com/mendixlabs/range-slider/blob/bee04f2d82e0d1c71d46a74ccc0b87b485845da6/src/components/RangeSlider.ts#L104

Try for now to set the marker  to less then 2, see if the widget runs

**Comment by rickyv3** [comment] 2018-03-26 14:49
@Andries-Smit @akileng56 I tried a marker of 0 and 1, and the widget still does not run. I should be able to get a test project out to you guys this week.

**Comment by rickyv3** [comment] 2018-03-26 18:53
See attached test project:

[RangeSlider_2.zip](https://github.com/mendixlabs/range-slider/files/1849121/RangeSlider_2.zip)

**Comment by Andries-Smit** [comment] 2018-03-27 13:01
Hi Ricky,

This issue reported is fixed in the release v1.1.4 https://appstore.home.mendix.com/link/app/52704/
Thanks to @akileng56 

Please note the issue occurred because the `Step value` was 0. This value was not allowed. It should show an error message from now on.

With kind regards,
Andries

**Closed as completed by Andries-Smit** 2018-03-27 13:01 UTC
